/**
 * Loading the prebuilt addon.
 *
 * What ships is `prebuilt.mjs` — the addon as base64 in the module graph,
 * generated by `native/build.ts` — because that is the form a bundler carries
 * correctly and an npm install carries just as well. Its `loadEmbedded()`
 * unpacks it to a temporary file, `dlopen`s it, and deletes it again. No
 * `.node` file is published, and none is committed, so the embed is not the
 * fallback: it is the only copy anything loads.
 *
 * `native/prebuilt/*.node` is a `zig build` output and stays one. Nothing
 * loads it — `pnpm build:native` re-embeds in the same command that writes it,
 * and `test/fuse/native.test.ts` is what compares the two. A loader that also
 * knew about the directory would only make "which copy am I running?" a
 * question with two answers, and it had exactly one useful answer: the embed.
 *
 * What is *not* here is anything that needs to know what the addon means:
 * `src/fuse/native.ts` does the error reshaping, because the errno table lives
 * in `src/errors.ts` and there is only ever one copy of it.
 *
 * {@link loadNative} is the whole of the interface, because it is the whole of
 * what `src/` asks for. Everything the tests want about the *embed* — which
 * platforms it carries, what bytes it decodes to — they read from
 * `prebuilt.mjs` itself, which is committed and therefore always there; there
 * is nothing for this file to forward.
 *
 * @module
 */

import { loadEmbedded } from "./prebuilt.mjs";

let cached;
let failure;

/**
 * Load the addon, once per process.
 *
 * A failure is remembered as well as a success: the answer cannot change while
 * the process runs, and retrying a `dlopen` on every mount attempt would turn
 * one clear error into a stutter.
 */
export function loadNative() {
  if (cached !== undefined) {
    return cached;
  }
  if (failure !== undefined) {
    throw failure;
  }
  try {
    cached = loadEmbedded();
  } catch (error) {
    failure = new Error(
      `mountx: could not load the native helper for ${process.platform}-${process.arch} ` +
        `${error instanceof Error ? error.message : String(error)}. ` +
        `It is only needed for unprivileged mounting; mounting as root does not use it. ` +
        `To build it from source: pnpm build:native`,
      { cause: error },
    );
    throw failure;
  }
  return cached;
}
